version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8876:80"
    depends_on:
      - app
    container_name: project_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - redis
    environment:
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
    container_name: project_app

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: lara
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8101:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: project_db

  node:
    image: node:18-alpine
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true
    container_name: project_node
    ports:
      - "5173:5173"
    command: "npm run dev"

  redis:
    image: redis:latest
    ports:
      - "63791:6379"
    container_name: project_redis

  adminer:
    image: adminer
    restart: always
    ports:
      - "8087:8080"

  mailer:
    image: mailhog/mailhog
    ports:
      - "8082:8025"


